---
name: bloc_custom_firebase
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  bloc: ^7.2.0
  cloud_firestore: null
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  google_ml_kit: ^0.7.2
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.8
  random_string: ^2.3.1
  persistent_bottom_nav_bar: ^4.0.2
  tcard: ^1.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/assets/svg/img1.svg
    - lib/assets/svg/img2.svg
    - lib/assets/img/sukuna.jpg
    - lib/assets/img/muzan.png


